module.exports = [
  {
    name: 'Nulla',
    price: 207,
    description: 'Culpa sed tenetur incidunt quia veniam sed molliti',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Corporis',
    price: 271,
    description: 'Nam incidunt blanditiis odio inventore. Nobis volu',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Minus',
    price: 295,
    description: 'Quod reiciendis aspernatur ipsum cum debitis. Quis',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Qui',
    price: 280,
    description: 'Occaecati dolore assumenda facilis error quaerat. ',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Similique',
    price: 262,
    description: 'Autem blanditiis similique saepe excepturi at erro',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Soluta',
    price: 109,
    description: 'Quos accusamus distinctio voluptates ducimus neque',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Quos',
    price: 247,
    description: 'Error voluptate recusandae reiciendis adipisci nec',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Sunt',
    price: 297,
    description: 'Tempora sed explicabo quae recusandae vitae debiti',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Nemo',
    price: 143,
    description: 'Id pariatur at modi esse distinctio error. Dolores',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Quo',
    price: 150,
    description: 'Explicabo distinctio labore eius. Culpa provident ',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Nobis',
    price: 195,
    description: 'Reprehenderit iste quos amet. Natus consequatur in',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Explicabo',
    price: 253,
    description: 'Nihil magni libero sapiente voluptate. Perspiciati',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Hic',
    price: 178,
    description: 'Ut assumenda soluta esse officia. Quos quaerat sus',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Occaecati',
    price: 199,
    description: 'Aut quam nisi libero distinctio. Temporibus rerum ',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Consequatur',
    price: 152,
    description: 'Iste repudiandae nostrum ea iste voluptate ducimus',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Assumenda',
    price: 236,
    description: 'Sint aperiam voluptatum laudantium laborum at debi',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Placeat',
    price: 115,
    description: 'Temporibus reiciendis inventore ratione asperiores',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Facilis',
    price: 130,
    description: 'In sequi cumque quisquam corrupti doloribus suscip',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Ratione',
    price: 117,
    description: 'Corrupti sint occaecati doloribus maiores. Exceptu',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Non',
    price: 230,
    description: 'Exercitationem debitis enim eum nemo necessitatibu',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Quaerat',
    price: 274,
    description: 'A similique facilis facilis. Excepturi repudiandae',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Fugiat',
    price: 167,
    description: 'Maiores eveniet dolores laudantium quae doloribus ',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Voluptas',
    price: 278,
    description: 'Quas a at officia quod in quod. Impedit deserunt t',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Repellendus',
    price: 285,
    description: 'Alias maiores soluta ab earum asperiores praesenti',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
  {
    name: 'Quibusdam',
    price: 209,
    description: 'Assumenda debitis voluptatem magnam temporibus mol',
    imageUrl: 'http://lorempixel.com/400/200/',
  },
];
